### ISSUE TITLE
Failed to download vulnerability DB

### ISSUE THREAD

**Issue by ButovOleg** [aquasecurity/starboard#161]
Launched the command for execution:
starboard find vulnerabilities deployment / nginx --namespace dev
Output:
E0926 05:36:47.401267    6188 manager.go:228] Container acad83d2-e151-4eca-83d5-d69f6e8b75f8 terminated with Error: 2020-09-26T09:36:16.611Z	INFO	Need to update DB
2020-09-26T09:36:16.611Z	INFO	Downloading DB...
2020-09-26T09:36:46.612Z	FATAL	failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get https://api.github.com/repos/aquasecurity/trivy-db/releases: dial tcp: i/o timeout
error: running scan job: job failed: BackoffLimitExceeded: Job has reached the specified backoff limit

starboard version 0.4
kubernetes version 1.18.5
centOS 7

**Comment by danielpacak** [comment]
Hi @ButovOleg We run Trivy as scan Job with BackoffLimit set to 1. However, I observed that often times the GitHub API is not responding. Hence, when Trivy is trying to download the DB file from https://api.github.com/repos/aquasecurity/trivy-db/releases the scan Job might fails.

1. Could you confirm that your cluster / network config allows access to https://api.github.com/repos/aquasecurity/trivy-db/releases
2. Could you try again and confirm that the issue persist?

**Comment by ButovOleg** [comment]
I changed the config, now another error:
error: unexpected EOF

**Comment by danielpacak** [comment]
All right @ButovOleg In order to help you and narrow down the root cause of all that I need more details. Could you provide:
1. Docker image reference that you use for your nginx deployment? (e.g. docker.io/library/nginx:1.16)
2. Confirm that your nginx deployment is actually running without any ImagePullBackoff errors
3. Provide the version of Starboard CLI that you're actually using (run `$ starboard version`). Is it 0.4.0?
4. Run the find vulnerabilities command and opt in to keep the scan job for troubleshooting:
   ```
   $ starboard find vuln deploy/nginx -v 3 --delete-scan-job=false
   ```
5. Once it fails, could you provide the output of the following commandst:
   ```
   $ kubectl -n starboard describe job <name of scan job>
   $ kubectl -n starboard describe pod <name of pod controlled by the scan job>
   $ kubectl -n starboard logs <name of pod controlled by the scan job>
   ```

**Comment by danielpacak** [comment]
Closing as stale issue without info required to further troubleshoot. If you still have such issue please open a new one with enough details to investigate on our end.
