### ISSUE TITLE
Figure out why integration test for kube-hunter command is failing on GitHub actions runner

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#165]
We have an integration test which runs kube-hunter command. However this tests fails when it's run on GitHub actions runner. It seems to be working fine in dev environment with local KIND cluster though.

**Comment by avats-dev** [comment]
I can also try this one, I'm familiar with github actions and `yaml`. Any help regarding this would be good too. Thanks.

**Comment by danielpacak** [comment]
> I can also try this one, I'm familiar with github actions and `yaml`. Any help regarding this would be good too. Thanks.

👋 @avats-dev I'm glad that you want take this one. In essence, we do have this integration test for kube-hunter, which is failing only on remote GitHub runner https://github.com/aquasecurity/starboard/blob/master/itest/starboard_cli_test.go#L876
I have no problems with it in my local dev though. (You can confirm that in your env by changing PDescribe to FDescribe, change the spec from pending to focused in order to speed things up.)

So we need to find out why kube-hunter scan job gets stuck on GitHub by adding maybe some verbose logs to the job itself, and/or adding some temporary steps around step for the integration tests run to describe the underlying Kubernetes job and see what is going on.

Maybe you can start also with this project https://github.com/nektos/act, which allows one to run the workflow locally?

As another hint I would specify the timeout in the integration test command (`starboard kube-hunter --delete-scan-job=false --scan-job-timeout=2m`) and then execute `kubectl describe job -n starboard` or `kubectl get events` to see if there's any obvious issue with the test or GitHub actions runner.

**Comment by avats-dev** [comment]
Thanks @danielpacak for the help, I'll look and try this, and get back to you with the updates.

**Comment by danielpacak** [comment]
👋 @avats-dev Do you have any updated on this issue? Please let me know if you continue working on that one. Otherwise I'll leave it unassigned.

**Comment by mlevesquedion** [comment]
I'd be interested in taking a look at this.

**Comment by danielpacak** [comment]
> I'd be interested in taking a look at this.

Please go ahead @mlevesquedion This one is really bothering me so it would be great if you find the root cause

**Comment by mlevesquedion** [comment]
I was able to run the kube-hunter test locally using [act](https://github.com/nektos/act). The test passes.

The exact command I used was:

```
act build -j itest-starboard -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04
```

I had to use the `nektos/act-environments-ubuntu:18.04` image since the regular image `act` uses to emulate `ubuntu-18.04` runners was missing too many things (the regular image is `node:12.6-buster-slim`). The `nektos/act-environments-ubuntu:18.04` is much bigger, though.

Since I haven't been able to observe the failure using `act`, I'm going to open a PR for debugging.

**Comment by mlevesquedion** [comment]
I've been investigating the issue in #326. I haven't seen the test fail yet, but it does take a long time to run, around 15 minutes. From my investigation, this seems to be caused by some intensive port scanning done by `kube-hunter`.

When `kube-hunter` detects that it's running in Azure, it determines what subnets to scan by querying the metadata API. On the GitHub runner, apparently the answer is `10.1.0.0/16`. That's a fair number of addresses to scan. Since `kube-hunter` scans 8 ports for each address (`[8001, 8080, 10250, 10255, 30000, 443, 6443, 2379]`), that amounts to a about half a billion scans.

When running locally, `kube-hunter` uses the node internal IP with a `/24` CIDR, which is very quick to scan.

I was able to obtain this information by setting `kube-hunter`'s log level to `DEBUG` in the `scan kubehunterreports` command.

One way to circumvent this is to ask `kube-hunter` to scan a specific CIDR, e.g. `127.0.0.1/32`. I was able to get the whole suite to pass by using this hack. See the results here: https://github.com/aquasecurity/starboard/pull/326/checks?check_run_id=1678709615

It might make sense to accept additional args for `kube-hunter` when the `kubehunterreports` scan is requested. This would allow us to pass some extra arguments in the test to avoid the excessive scanning.

WDYT?

**Comment by danielpacak** [comment]
Amazing analysis @mlevesquedion ! I checked your conclusion with @danielsagi , creator of kube-hunter, and he confirmed your reasoning. He also pointed out that there's the `--quick` flag to circumvent excessive port scanning, which would solve the problem with our GitHub Actions runner. I actually tried this flag and it worked!

That said, I'd add the `kube-hunter.quick` configuration parameter which would allow us to enable quick port scanning before we run the `starboard scan kubehunterreports` command in the integration test.

**Comment by mlevesquedion** [comment]
Thank you! I've opened a PR implementing support for a `quick` configuration parameter in #331.

As a side note: is the `--quick` flag for `kube-hunter` documented somewhere? I couldn't find the docs for `kube-hunter`, but I did some digging in the codebase and it looks like the flag has been available for a while.

**Comment by danielpacak** [comment]
> Thank you! I've opened a PR implementing support for a `quick` configuration parameter in #331.
> 
> As a side note: is the `--quick` flag for `kube-hunter` documented somewhere? I couldn't find the docs for `kube-hunter`, but I did some digging in the codebase and it looks like the flag has been available for a while.

I think the flag is not mentioned in the README. It's kind of tribal knowledge. @danielsagi do you think we can document as officially supported flag?
