### ISSUE TITLE
Handle Kubernetes cluster config errors

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#20]
Similarly to the `kubectl` command, we should display a nice message when there's a problem reading cluster config files:

```
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config
```

**Comment by danielpacak** [comment]
> @danielpacak can this assign to me ?

Sure thing @evalsocket I'm happy to assign to you!

**Comment by danielpacak** [comment]
@evalsocket could you update us on this one please? Are you available to work on this one? Otherwise we could leave it as unassigned.

**Comment by evalsocket** [comment]
@danielpacak i will start working on it from today

**Comment by krol3** [comment]
I could help with this issue @danielpacak

**Comment by mlevesquedion** [comment]
@krol3 are you still working on this?

If not, I would be interested in taking a look.

**Comment by krol3** [comment]
@mlevesquedion yeah you could take a look.  Thanks

**Comment by mlevesquedion** [comment]
@danielpacak could you give some additional info on how to produce this error message with `kubectl`?

Locally, When I remove `.kube/config` and unset `KUBECONFIG`, `kubectl` gives me this error:

```
$ kubectl get pods      
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

(I am using the latest `kubectl`, GitVersion: v1.20.1)

`starboard` gives me a similar error:

```
$ starboard config
error: Get "http://localhost:8080/api/v1/namespaces/starboard/configmaps/starboard": dial tcp [::1]:8080: connect: connection refused
```

(Using bin/starboard, on the main branch)

The issue seems to be that the config loading code sets a default value of `Server: http://localhost:8080`, which makes the config non-empty...

---

From my reading of the code in `k8s.io/cli-runtime` and `k8s.io/client-go`, it looks like starboard should get the same error message as `kubectl` "for free" since starboard CLI uses the Go client. Indeed, the error message you refer to in the original post is defined in `k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go`, and this error message is returned by `ConfigFlags.ToRESTConfig()` if the config is empty.

**Comment by danielpacak** [comment]
Indeed, it seems that things might have changed since I reported this issue. I believe that we bumped up client-go in the meantime.

I cannot get the desired message as originally reported as well. If the current message is meaningful we can close this one as invalid.

**Comment by mlevesquedion** [comment]
Yeah, I think there's not much we can do, this looks like a `client-go` issue to me. I'll open an issue there. It seems to me that we should be seeing the error message you mentioned originally, but maybe this is WAI.

**Comment by danielpacak** [comment]
Closing according to the comments above.
