### ISSUE TITLE
[operator] Design and implement Trivy DB caching

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#213]
We run Trivy scans as ephemeral Jobs scheduled by Kubernetes. Each scan Job in its init container pulls the latest version of Trivy DB from GitHub (https://github.com/aquasecurity/trivy-db). This might lead to unnecessary network traffic and eventually lead to GitHub relate limit.

See https://github.com/aquasecurity/starboard/discussions/209 for great suggestions.

**Comment by StatingPrism** [comment]
Hey, I'm pretty new to the project but would like to help with this issue.
Is the solution to this asking to have a cache of the Trivy db on the host machine that has the containers, and have the `initContainers` variable in _/pkg/find/vulnerabilities/trivy/scanner.go_ take from the cache if there hasn't been any updates to the db since the last scan? Then if it's too old have the host update the cache before pulling from it?

**Comment by danielpacak** [comment]
👋 @StatingPrism I was thinking more about the Starboard Operator. I'm not sure if we need such a cache for the CLI interface.

Anyway, caching a Trivy DB on a host and using hostPath volume mounts is a valid option, however some people might not like it because of PodSecurityPolicies that might prevent this type of volume. That said, I'd start with a discussion to evaluate and brainstorm this and other options before we proceed with writing any code.

See #209 for other options mentioned by @consideRatio

**Comment by consideRatio** [comment]
I think its motivated to have some kind of k8s local cache service running, so that access to the vulnerability database would look something like this.

Trivy scanner pod <--> k8s local cache service <--> Vuln database at GitHub

If implemented like this, we would minimize requests to GitHub to the extent that we likely won't need any API key, and if we do it is a clear place to configure it, we can for example mount it from an optional k8s Secret as an environment variable on the pod running the k8s local cache service.

I think there are three choices to run the k8s local cache service, and I'm unsure what make most sense.

1. __Dedicated pod__
   May or may not lead to the need to maintain another dedicated docker image, but scripts etc can be mounted etc.
2. __Sidecar container to the starboard-operator Pod__
   Same drawback as above, but may benefit from having the same kind of configuration with regards to nodeSelector and such that one may want to set for the starboard-operator pod.
3. __Part of the starboard-operator binary__
   By doing this, the starboard-operator binary needs to function as a webserver etc for this kinds of requests alongside its other duties. I think this is the least complicated option from a k8s deployment perspective, I currently lean towards this as the best option but I'm not sure and I don't know much about Go-lang.
   
   If this option is used, one should also consider if one will use a dedicated port to listen on, or use some already existing port for incoming network traffic.
   
   If an additional port is used, one would configure another entry in the k8s Service resource for the starboard-operator service part of the Helm chart, and then just let the trivy pods assumed to run in the same namespace as the starboard-operator Pod request the cached vuln database from http://<k8s-service-name>:<k8s-service-port-for-cached-db>/

**Comment by marsom** [comment]
Trivy has a client / sever mode, you could easily start one or more in server mode and use trivy in cleint mode to scan images. the only option starboard should have: --trivy-remote

see https://github.com/aquasecurity/trivy#client--server

**Comment by danielpacak** [comment]
👋 @marsom Yes that's a good point and sth that I'm currently implementing. Trivy stand-alone mode would be the default one, but you could configure Trivy server URL (and optional token) to leverage Trivy client / server mode. Below you can find a high level diagram of such enhancement.

![starboard-trivy-cs](https://user-images.githubusercontent.com/1322923/99060620-95041580-25a0-11eb-9aac-aba62e00d423.png)
