### ISSUE TITLE
Upgrade Polaris to 1.0

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#33]
**Describe the problem/challenge you have**

Currently we pinned [Polaris] image to `quay.io/fairwinds/polaris:cfc0d213cd603793d8e36eecfb0def1579a34997` and we're running `polaris audit --log-level error` command as a Kubernetes Job to check all workloads and create [`configauditreports`](https://github.com/aquasecurity/starboard/blob/master/kube/crd/configauditreports-crd.yaml) resources (see an [example]( https://github.com/aquasecurity/starboard/blob/master/kube/examples/configauditreports.yaml)).

**Describe the solution you'd like**

We'd like to:
- Upgrade to the latest and greatest Polaris
- Review and adopt `configauditreports` definition to store configuration audits
  - Add OpenAPI Spec to validate `configauditreports` payload compatible with Polaris 1.0 output
- Keep the `configauditreports` definition flexible for other vendors to integrate with Starboard

**Anything else you would like to add:**

This might be related to #29 

[polaris]: https://github.com/FairwindsOps/polaris

**Comment by rbren** [comment]
A few breaking changes in our output format in 1.0:
* we now support checks at the controller level, as well as at the pod and container levels
* the list of containers is now an array rather than an object, to match the format of `podSpec`
* severity `error` has been changed to `danger`
* the list of checks is now an object keyed by check ID, rather than an array

I think the first three changes would be valuable to bring into the ConfigAuditReports CRD. However, I could see wanting to keep the list of checks as an array, rather than an object keyed by ID, since other implementers of this scanner might have different IDs, and might duplicate an ID. For example, prior to 1.0, we had two different checks named `capabilities` (one warning, one danger)
