### ISSUE TITLE
[cli] The get vulnerabilities command should resolve reports owned by any object in the same workload hierarchy

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#339]
If a VulnerabilityReport is owned by ReplicaSet (the default behaviour of the operator) you cannot retrieve it with starboard CLI by specifying the Deployment as a command-line arg

```
starboard get vulnerabilities deploy/nginx
```

If the VulnerabilityReport is not owned by a Deployment, the implementation should lookup the active ReplicaSet / revision and then find the report.

Similarly, when you specify a pod name as command-line argument it should lookup its parent ReplicaSet and find the report at ReplicaSet level.

EDIT: Related to that is to think about the interface that we currently provide for security reports, which is somehow mixing what `kubectl get` and `kubectl describe` commands do for built in resources. In other words, we should consider adding `starboard describe <report type> <workload>` command.

**Comment by mlevesquedion** [comment]
I would be interested in working on this.

**Comment by danielpacak** [comment]
That's awesome @mlevesquedion Please go ahead.

Notice that I edited the description to mention that we may want to introduce `starboard describe vulnerabilityreport/deployment-nginx-nginx` command to follow the `kubect get/describe` semantics. However, I don't think it's in scope of this change. We can improve the UX step by step.

**Comment by mlevesquedion** [comment]
Sorry about the lack of updates, I've been fairly busy lately. I have a bit more time now, and I plan to open a PR for this this week.

So far I have written a test case that validates that if you have a vulnerability report on a deployment, and you `get` the report on the corresponding replicaset, it will find and return the report that's on the deployment. The test is passing, but I will need to clean up a few things.

I plan to add more test cases, e.g. `pod --> deployment` and `pod --> replicaset`.

I will need to change both `pkg/vulnerabilityreport/io.readWriter` and `pkg/vulnerabilityreport/io.crReadWriter`. I'll avoid duplication if I can.

Also, I will need to update the generated code so that I can get `replicasets` and `pods` and whatnot in the `readWriter`.

**Comment by danielpacak** [comment]
No worries @mlevesquedion Take your time with this change and do let me know if you need any help.

I would also suggest that you focus on CLI and ReadWriter implementation that relies on client-go library. The first / main thing that we want to fix is to retrieve the report by Deployment or pod name even though the actual report is stored by the operator at active ReplicaSet level.

I'm not sure that the operator should be aware of any reports generated by the CLI. At least maybe not is scope of this change.
