### ISSUE TITLE
Some parameters cannot be defined within values.yaml

### ISSUE THREAD

**Issue by bgoareguer** [aquasecurity/starboard#435]
**What steps did you take and what happened:**
Install starboard-operator with the Helm chart.
There is no way to configure all parameters that are stored in the `starboard` ConfigMap (e.g. Trivy server URL)

**What did you expect to happen:**
We should be able to configure all parameters from the `values.yaml` file.

**Environment:**

- Starboard version: 0.9.2
- Kubernetes version: 1.20.4
- OS: Ubuntu 18.04

**Comment by danielpacak** [comment]
We separate generic Starboard Operator config params (e.g. metrics endpoint, target namespaces) from plugins config. Trivy is just a plugin, therefore its configuration is separated. You're supposed to edit starboard ConfigMap to adjust default scanner settings. Only generic Starboard config can be change with Helm values.

We'll further split the "monolith" `starboard` ConfigMap into `trivy` ConfigMap, `polaris` ConfigMap, etc. Otherwise this configuration model does not scale with number of plugins that we plan to add.

**Comment by danielpacak** [comment]
Got you point. Actually I like the idea of having a separate ConfigMap template for each plugin. After all plugins are currently in-tree so this approach makes sense. Is this something you'd like to contribute?

**Comment by bgoareguer** [comment]
Yes, sure!

**Comment by danielpacak** [comment]
Great! Since we haven't started refactoring the `starboard` ConfigMap yet, let's just add template for it in phase 1. That would be something you requested. After refactoring ConfigMap we'll take care of updating the Helm chart.
