### ISSUE TITLE
Add tolerations to vulnerability scan jobs spawned by Starboard

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#538]
In a cluster where (all) nodes are [tainted](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) scan jobs created programmatically by Starboard would fail. See also #507.
One solution would be to configure tolerations at startup, e.g. in the `starboard` ConfigMap.

1. [ ] To get started add tolerations to scan Jobs scheduled by a vulnerability scanner.
2. [ ] Make sure that new code is tested

**Comment by champness** [comment]
@danielpacak This issue talks about adding tolerations to the `starboard` ConfigMap, but would it be more correct to say that the toleration should be added to the PodSpec?

**Comment by champness** [comment]
@danielpacak Another point of clarification: When you say that the scan jobs fail, you're referring to the fact that the scanner pod never get scheduled onto a node because the taint prevents it, is that correct?  I can confirm that in my minikube single-node cluster, if I taint the node, then the `starboard scan` command hangs, and I can see the starboard pod stuck in `Pending` status until I remove the taint.

**Comment by danielpacak** [comment]
To be precise we want to configure which taints Starboard accepts by defining some config param to the starboard ConfigMap. Tolerations themselves are added to the PodSpec.

We consider a job that has stuck as failed one because we're not getting a VulnerabilityReport (unless you remove taints). This actually would be another enhancement / PR to fail fast instead of waiting forever.
