### ISSUE TITLE
scan-cisbenchmark - failure in a Windows system call: The user name or password is incorrect.

### ISSUE THREAD

**Issue by goosedeersolutions** [aquasecurity/starboard#592]
I have a Kubernetes cluster that consists of a Windows node and a Linux node. When I install the starboard operator, it triggered two job - scan-cisbenchmark - one for each node. The job running on the Linux node ran successfully, however the job for the Windows node is throwing an error:

```
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "scan-cisbenchmark-5774f95bfc-d226t": Error response from daemon: container 4c38e9eb4831710b915621748a2353a13235b04f6e8523ebb333fc0a932dda10 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"CommandLine":"cmd /S /C cmd /c ping -t localhost","User":"0:0","WorkingDirectory":"C:\\","CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```

I may be being an idiot but I didn't see in the guide where you would add this username or password.

**Comment by danielpacak** [comment]
👋 @goosedeersolutions KubeBench can only be run on Linux nodes. Therefore, for Starboard CLI we skip Windows nodes explicitly by looking at the `kubernetes.io/os` (see [here](https://github.com/aquasecurity/starboard/blob/main/pkg/cmd/scan_ciskubebenchreports.go#L78)). IIRC we haven't done that for the operator so that would be a bug. Could you just confirm what is the value of the `kubernetes.io/os` label for the Windows node or any other labels / annotations that distinguish node OS.
