### ISSUE TITLE
KubeBench scanner pod run with excessive permissions

### ISSUE THREAD

**Issue by kfox1111** [aquasecurity/starboard#665]
cis jobs have this in its config:
```
      automountServiceAccountToken: true
      serviceAccount: starboard-operator
```

The starboard-operator service account has permissions to read every secret in the cluster so that it can setup the scanning properly. Since the cis jobs run on all nodes, this distributes out to all the nodes a secret that can download all the secrets from all the nodes.

The cis jobs should have their own service account with restricted permissions with just enough access to upload the cis results.

Perhaps the vulnerability scanning jobs should also have a restricted service account. They currently have the servce account token turned off though, so not currently as bad.

**Comment by danielpacak** [comment]
I believe this discussion is related to #646 . If I understand correctly the idea is to run scanner pods (Trivy, Polaris, Conftest, KubeBench, KubeHunter, etc.) with dedicated service accounts instead of reusing the service account used to run the operator's pod. Let's continue this discussion under #646

**Comment by kfox1111** [comment]
Yeah. that discussion looks to be the same. thanks.
